name: Build password_generator EXE

on:
  workflow_run:
    workflows: ["Run Tests and Save Reports"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Оновлено до останньої версії

    - name: Set up Python
      uses: actions/setup-python@v5  # Оновлено до v5 для стабільності
      with:
        python-version: '3.10'  # Чітко вказано Python 3.10
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      if: success()
      run: |
        pyinstaller -F -i logo.ico --add-data "logo.ico;." --add-data "logo.png;." password_generator.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: password_generator_exe
        path: dist/password_generator.exe
