name: Run Tests and Save Reports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Оновлено до v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Оновлено до v5
      with:
        python-version: '3.10'  # Чітко вказано Python 3.10
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests with XML report
      run: |
        python -m xmlrunner discover -s test -o test-reports

    - name: List test reports directory
      run: |
        ls -la test-reports || echo "Немає звітів тестів"

    - name: Upload test results
      if: success() || failure()  # Завантажувати звіти навіть при помилці
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: test-reports/*.xml
