name: Run Tests and Save Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Можна вибрати іншу ОС, якщо потрібно

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Якщо є файл requirements.txt

    - name: Run unit tests with XML report
      run: |
        python -m xmlrunner discover -s tests -o tests/

    
    - name: Save test results
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: ./tests/test_report.xml  # Ти можеш згенерувати звіт у форматі JUnit або XML у своєму тесті, якщо це потрібно
