name: Run Tests and Save Reports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests with XML report
      run: |
        python -m xmlrunner discover -s tests -o test-reports

    - name: List test reports directory
      run: |
        ls -la test-reports || echo "No test reports found"

    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: test-reports/*.xml
